#!/usr/bin/env python3
"""
Regenerates tools/sprites.js — the base64-encoded sprite images the level
editor draws. Run this whenever you add or change art.

    python build-sprites.py

To add a new sprite: drop the PNG under Ashenveil.Core/Content/Sprites/... and
add one line to FILES below (key -> path relative to the Sprites folder).
The key is what the editor references via the `img` field in its config.
"""

import base64
import json
import os

# Folder that paths below are relative to.
SPRITES_DIR = os.path.join(
    os.path.dirname(__file__), "..", "Ashenveil.Core", "Content", "Sprites"
)
OUTPUT = os.path.join(os.path.dirname(__file__), "sprites.js")

# key -> path (relative to SPRITES_DIR). Add new art here.
FILES = {
    "grass":      "Tiles/grass.png",
    "dirt":       "Tiles/dirt.png",
    "dirt_road":  "Tiles/straight_dirt_road.png",
    "dirt_cross": "Tiles/cross_dirt_road.png",
    "tree_1":     "Objects/Tree_Small.png",
    "tree_2":     "Objects/Tree_Medium.png",
    "tree_3":     "Objects/Tree_Large.png",
}


def main():
    out = {}
    missing = []
    for key, rel in FILES.items():
        path = os.path.join(SPRITES_DIR, rel)
        if not os.path.exists(path):
            missing.append(rel)
            continue
        with open(path, "rb") as f:
            out[key] = "data:image/png;base64," + base64.b64encode(f.read()).decode()

    if missing:
        print("WARNING: missing files (skipped):")
        for m in missing:
            print("  -", m)

    with open(OUTPUT, "w") as f:
        f.write("// Auto-generated by build-sprites.py. Do not edit by hand.\n")
        f.write("const SPRITES = " + json.dumps(out, indent=0) + ";\n")

    total = sum(len(v) for v in out.values())
    print(f"Wrote {OUTPUT} — {len(out)} sprites, {total:,} chars")


if __name__ == "__main__":
    main()
